### PR TITLE
Two message queues to differentiate between sending to client and player

### LINKED ISSUE #43: Interprocess communication not working fully
~~It seems as if a 2nd process can determine that another process is running, but the messages don't appear to be reaching the other process.~~

Often times the client sends a message to itself because all instances read from the same message queue.

Suggested solution
---------------------
Create two queues:

- one for sending from the client to the player
- one for sending from the player to the client

### PR DESCRIPTION
**Pull request by Dyrand**
Fixes #43

### CODE REVIEW

File: src/main.cpp [hunk 1]
```diff
@@ -223,7 +224,7 @@ int main( int argc, char *argv[]) {
                     std::cout << "Toggle File Loop" << std::endl;
                     song.setMode(LOOP_FILE);
                 } else {
-                    mq.SendMessage("Invalid");
+                    mq_to_client.SendMessage("Invalid");
                 }
                 //Delay to prevent sending message to self
                 std::this_thread::sleep_for(std::chrono::milliseconds(1));
```
Comment (MonJamp) [inline src/main.cpp]: I don't think we need the delay anymore. You could probably remove this line and amend the changes to this commit.

**Review by MonJamp — CHANGES_REQUESTED** [review]

**Review by MonJamp — APPROVED** [review]
